pineapple_rest:
    resource: "BRS\\PineappleBundle\\Controller\\PineappleController"
    type:     rest
    
widget_rest:
    resource: "BRS\\PineappleBundle\\Controller\\BlockController"
    type:     annotation
    defaults: {_format: json}
    options:
        expose: true
        
page_rest:
    resource: "BRS\\PineappleBundle\\Controller\\PageController"
    type:     rest
    options:
        expose: true