services:
    
    brs.configurator:
        class: BRS\PineappleBundle\Configurator\RoleConfigurator
        arguments:
            container: @service_container
    
    brs.twig.pineapple_extension:
        class: BRS\PineappleBundle\Twig\PineappleExtension
        arguments:
            configurator: @brs.configurator
        tags:
            - { name: twig.extension }
    
    brs.pineapple.widget_list:
        class: BRS\PineappleBundle\Block\PineappleWidgetListBlockService
        arguments:
            name: brs.pineapple.widget_list
            templating: @templating
            container: @service_container
        tags:
            - { name: sonata.block }
    
    brs.pineapple.base_header:
        class: BRS\PineappleBundle\Block\BaseHeaderBlockService
        arguments:
            name: brs.pineapple.base_header
            templating: @templating
            selector: @sonata.page.site.selector
            cms_manager: @sonata.page.cms_manager_selector
        tags:
            - { name: sonata.block }
            - { name: brs.pineapple_widget, categories: "Headers", class: header, title: "Base Header", description: "Base Header" }