services:
    
    brs.configurator:
        class: BRS\PineappleBundle\Configurator\RoleConfigurator
        arguments:
            container: @service_container
    
    brs.twig.pineapple_extension:
        class: BRS\PineappleBundle\Twig\PineappleExtension
        arguments:
            configurator: @brs.configurator
        tags:
            - { name: twig.extension }
    
    brs.page.manager.block:
        class: BRS\PineappleBundle\Manager\BlockManager
        arguments:
            container: @service_container
            entityManager: "@doctrine"
            class: %sonata.page.block.class%
            
    brs.pineapple.widget.media_library:
        class: BRS\PineappleBundle\Block\MediaLibraryBlockService
        arguments:
            name: brs.pineapple.widget.media_library
            templating: @templating
            container: @service_container
        tags:
            - { name: sonata.block }
    
    brs.pineapple.form.type.pineapple_media:
        class: BRS\PineappleBundle\Form\Type\PineappleMediaType
        arguments:
            container: @service_container
        tags:
            - { name: form.type, alias: pineapple_media }
    
    brs.pineapple.widget.text:
        class: BRS\PineappleBundle\Block\TextBlockService
        arguments:
            name: brs.pineapple.widget.text
            templating: @templating
        tags:
            - { name: sonata.block }
            - { name: brs.pineapple_widget, categories: "Content", class: text, title: Text, description: "An editable text box", icon: "/lib/images/core/content.text.png" }
    
    brs.pineapple.widget_list:
        class: BRS\PineappleBundle\Block\PineappleWidgetListBlockService
        arguments:
            name: brs.pineapple.widget_list
            templating: @templating
            container: @service_container
        tags:
            - { name: sonata.block }
    
    brs.pineapple.base_header:
        class: BRS\PineappleBundle\Block\BaseHeaderBlockService
        arguments:
            name: brs.pineapple.base_header
            templating: @templating
            selector: @sonata.page.site.selector
            cms_manager: @sonata.page.cms_manager_selector
        tags:
            - { name: sonata.block }
            - { name: brs.pineapple_widget, categories: "Headers", class: header, title: "Base Header", description: "Base Header" }

    brs.pineapple.jumbotron_header:
        class: BRS\PineappleBundle\Block\HeaderJumbotronBlockService
        arguments:
            name: brs.pineapple.jumbotron_header
            templating: @templating
            selector: @sonata.page.site.selector
            cms_manager: @sonata.page.cms_manager_selector
        tags:
            - { name: sonata.block }
            - { name: brs.pineapple_widget, categories: "Headers", class: header, title: "Jumbotron Header", description: "Jumbotron Header", icon: "/lib/images/core/header.jumbotron.png" }

    brs.pineapple.service.header.splash:
        class: BRS\PineappleBundle\Block\HeaderSplashBlockService
        arguments:
            name: brs.pineapple.service.header.splash
            templating: @templating
            selector: @sonata.page.site.selector
            cms_manager: @sonata.page.cms_manager_selector
        tags:
            - { name: sonata.block }
            - { name: brs.pineapple_widget, categories: "Headers", class: text, title: "Header Splash", description: "Header Splash" }

    brs.pineapple.service.header.full_image:
        class: BRS\PineappleBundle\Block\HeaderFullImageBlockService
        arguments:
            name: brs.pineapple.service.header.full_image
            templating: @templating
            selector: @sonata.page.site.selector
            cms_manager: @sonata.page.cms_manager_selector
        tags:
            - { name: sonata.block }
            - { name: brs.pineapple_widget, categories: "Headers", class: text, title: "Header Full Image", description: "Header Full Image" }

    brs.pineapple.service.content.featurette:
        class: BRS\PineappleBundle\Block\ContentFeaturetteBlockService
        arguments:
            name: brs.pineapple.service.content.featurette
            templating: @templating
            media_manager: @sonata.media.manager.media
        tags:
            - { name: sonata.block }
            - { name: brs.pineapple_widget, categories: "Content", class: text, title: "Content Featurette", description: "Content Featurette", icon: "/lib/images/core/content.featurette.png" }

    brs.pineapple.service.content.color_block:
        class: BRS\PineappleBundle\Block\ColorBlockBlockService
        arguments:
            name: brs.pineapple.service.content.color_block
            templating: @templating
            selector: @sonata.page.site.selector
            cms_manager: @sonata.page.cms_manager_selector
        tags:
            - { name: sonata.block }
            - { name: brs.pineapple_widget, categories: "Content", class: text, title: "Color Block", description: "Color Block" }
