services:
    
    brs.configurator:
        class: BRS\PineappleBundle\Configurator\RoleConfigurator
        arguments:
            container: @service_container
    
    brs.twig.pineapple_extension:
        class: BRS\PineappleBundle\Twig\PineappleExtension
        arguments:
            configurator: @brs.configurator
        tags:
            - { name: twig.extension }