parameters:

services:
    
    brs.configurator:
        class: BigRoomStudios\PineappleBundle\Configurator\RoleConfigurator
        arguments:
            container: @service_container
            config_path: 'test'
    
    brs.twig.pineapple_extension:
        class: BigRoomStudios\PineappleBundle\Twig\PineappleExtension
        arguments:
            configurator: @brs.configurator
        tags:
            - { name: twig.extension }